### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by mrzbigniew** [chicojunior/epam-angular-mentoring#7]
https://github.com/chicojunior/epam-angular-mentoring/blob/8cc9c6e86e2e163b59e71ef129e8493b4369d5f4/.travis.yml#L13

Please move it to repository settings: https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

Anyone will be able to do anything with your firebase app if he gets this token

**Comment by chicojunior** [comment]
The issue is resolved on PR #6.
